using System;
using System.Windows.Forms;
using OneTrueError.Reporting.Reporters;

namespace OneTrueError.Reporting.WinForms
{
    /// <summary>
    /// Default dialog which is shown when an error has been caught
    /// </summary>
    public partial class ReportDialog : Form
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="ReportDialog"/> class.
        /// </summary>
        public ReportDialog(string reportErrorId)
        {
            if (reportErrorId == null) throw new ArgumentNullException("reportErrorId");
            ReportId = reportErrorId;
            InitializeComponent();
            /*feedback1.Visible = OneTrue.Configuration.AskUserForDetails;
            feedback2.Visible = OneTrue.Configuration.AskUserForDetails;
            allowCollect1.Visible = OneTrue.Configuration.AskUserForPermission;
            allowCollect2.Visible = OneTrue.Configuration.AskUserForPermission;
            allowCollect3.Visible = OneTrue.Configuration.AskUserForPermission;
            allowCollect4.Visible = OneTrue.Configuration.AskUserForPermission;*/

            if (!OneTrue.Configuration.AskUserForDetails)
            {
                controlsPanel.Controls.Remove(errorDescription1);
            }
            if (!OneTrue.Configuration.AskForEmailAddress)
            {
                controlsPanel.Controls.Remove(notificationControl1);
            }
            if (!OneTrue.Configuration.AskUserForPermission)
            {
                btnCancel.Hide();
            }

            var height = CalculateFormHeight();
            Height = height;
            if (controlsPanel.Controls.Count == 2)
                Width = 550;

        }

        private int CalculateFormHeight()
        {
            var height = 0;
            foreach (Control control in controlsPanel.Controls)
            {
                height += control.Height;
            }
            height += panel1.Height;
            height += 100;
            return height;
        }

        /// <summary>
        /// CreateReport id (generated by OneTrueError)
        /// </summary>
        /// <remarks>Identifies this exception instance.</remarks>
        public string ReportId { get; private set; }

        /// <summary>
        /// Exception message
        /// </summary>
        public string ExceptionMessage
        {
            set
            {
                lblErrorMessage.Text = value;
            }
        }

        private void label2_Click(object sender, EventArgs e)
        {

        }


        private void ReportDialog_Load(object sender, EventArgs e)
        {

        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void flowLayoutPanel1_Paint(object sender, PaintEventArgs e)
        {
        }

        private void flowLayoutPanel1_Resize(object sender, EventArgs e)
        {
            controlsPanel.SuspendLayout();

            foreach (Control control in controlsPanel.Controls)
            {
                control.Width = controlsPanel.Width - 10;
            }
           
            controlsPanel.ResumeLayout();

        }

        private void btnSubmit_Click_1(object sender, EventArgs e)
        {
             var info = errorDescription1.UserInfo;
            var email = notificationControl1.Email;

            if (!string.IsNullOrEmpty(info) || !string.IsNullOrEmpty(email))
            {
                OneTrue.SendReport(ReportId, new UserSuppliedInformation(info, email));
            }
            else
            {
                OneTrue.SendReport(ReportId);
            }
            Close();
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void errorDescription1_Load(object sender, EventArgs e)
        {

        }


    }
}
